VPBUS_TEST_VERSION = 1.0
VPBUS_TEST_SITE = $(BR2_EXTERNAL)/package/vpbus_test
VPBUS_TEST_SITE_METHOD = local
VPBUS_TEST_LICENSE = GPLv3+


define VPBUS_TEST_INSTALL_TARGET_CMDS
	
endef

$(eval $(cmake-package))
